from django.urls import path

from . import views

urlpatterns = [
    path('student/',views.studentListView.as_view(),name='student'),        
    path('newstudent/',views.newstudentListView.as_view(),name='newstudent'), 
    path('student/<int:pk>',views.stuDetailView.as_view(),name='studetail'),        
    # path('det/<int:id>',views.stuDetailView.as_view(),name='det'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
]